POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MTcyNGI4YzI5YmUxN2FmMWNmMjhkNzciLCJpYXQiOjE2MzQ5NzA2NDAsImV4cCI6MTYzNTA1NzA0MH0.HHGIGN5erdUrfMlDctcetZ92q2taFPsoruR44mlfBHE

{
  "title": "I now have custom tokenExtractor middleware in just the blogs route",
  "author": "fs-helsinki",
  "url": "https://tokenUser.org",
  "likes": 33
}

